### PR TITLE
Add shiny app template

### PR DESCRIPTION
**Pull request by RosalynLP**
@alan-y We discussed before that this would be a useful addition to the package.

Before merging we'll need to run it past a few people to finesse look of the dashboard, and check if there is any official guidance anywhere which needs adhered to.

### CODE REVIEW

**Comment by alan-y** [comment]
wow this looks great - I'm not the best person for reviewing shiny-related things (although I intend to learn and it's one of my personal goals to properly understand it) but I can test later.

**Comment by RosalynLP** [comment]
Thanks, it still needs a bit of work before it'll be ready to review properly but at I checked that it at least makes a basic app from the menu and also using the function directly. I can also find some other people to help review that are used to working on shiny apps.

**Review by rubenv95 — APPROVED** [review]
I like the set-up and I think the minimalist approach is good. 
Only thing I noticed was that the indentation wasn't quite right, but otherwise it seemed good to me. 
My last thought actually as well is perhaps an explanation of the css script in README? If someone is not confident in css styles they might not quite know why certain styles are being applied or how to change them - so a wee overview of what gets applied might be helpful. 

Great work - going to be a wonderful addition to the package. Happy to help get this advertised.

**Comment by alan-y** [comment]
Is it worth mocking up an example of something with `plotly` and `DT` (or whatever the recommended package is for data tables) to show examples of using these for a dashboard? In the Rmd templates, we have a mock example with ggplot2 and flextable and might be helpful for users getting started.

**Comment by RosalynLP** [comment]
@alan-y yep, @rubenv95 and I were discussing this today about how much stuff to put in the app and the trade off between providing a template and not imposing too much personal style on it. Perhaps a very basic plotly plot and data table are a good compromise. One thing we thought might be good in the long run would be to make a github repo which is a demo shiny dashboard, and we could link to that in the README

**Comment by alan-y** [comment]
Hi @RosalynLP I've tested this briefly and all looks great except I ran into a couple of issues:

For some reason, the images don't seem to work for me when I run the app - I can get these to work if I manually re-download from Github but not sure if others may experience this or just me (if there's something weird with my setup). One workaround that may work is to store these in `inst` so that users have these offline but we'd need to re-write the code a bit to load the images from the package directory once installed. I'm also thinking of storing things like the gitignore or script template in `inst` as we're starting to refer to these in multiple functions and it'd probably make maintenance easier if we store these centrally in text files...

I also can't seem to use the overwrite option in either the PHS project or PHS Shiny templates when I try to do this through the menu - it just says that it doesn't allow it to create the project if the directory already exists. I'm not sure why but one change that's needed anyway in `phsproject()` is to add the overwrite argument into the function as it's only currently in the code but not in the list of arguments.

When your code refers to this link https://use.fontawesome.com/releases/v6.1.1/css/all.css - is there any way to track the url of the latest version or will we have to update this link periodically as part of maintenance?

Minor change: in `shiny_app_template.R` line 2, please change to `author <- paste('# Original author(s):', author)`
This will match what we have in the new script function.

**Comment by RosalynLP** [comment]
> Hi @RosalynLP I've tested this briefly and all looks great except I ran into a couple of issues:
> 
> For some reason, the images don't seem to work for me when I run the app - I can get these to work if I manually re-download from Github but not sure if others may experience this or just me (if there's something weird with my setup). One workaround that may work is to store these in `inst` so that users have these offline but we'd need to re-write the code a bit to load the images from the package directory once installed. I'm also thinking of storing things like the gitignore or script template in `inst` as we're starting to refer to these in multiple functions and it'd probably make maintenance easier if we store these centrally in text files...
> 
> I also can't seem to use the overwrite option in either the PHS project or PHS Shiny templates when I try to do this through the menu - it just says that it doesn't allow it to create the project if the directory already exists. I'm not sure why but one change that's needed anyway in `phsproject()` is to add the overwrite argument into the function as it's only currently in the code but not in the list of arguments.
> 
> When your code refers to this link https://use.fontawesome.com/releases/v6.1.1/css/all.css - is there any way to track the url of the latest version or will we have to update this link periodically as part of maintenance?
> 
> Minor change: in `shiny_app_template.R` line 2, please change to `author <- paste('# Original author(s):', author)` This will match what we have in the new script function.

Thanks for this @alan-y 

- Putting the images in inst maybe seems like the best idea in this case. It seemed to work for me and @rubenv95 as is but having them directly downloaded is probably best practice
- Other central text files in inst is also a good idea, could even move the .css and other big blocks of text in there
- You're right, I forgot to add overwrite into the phsproject function. However it was working for me and @rubenv95 in the shiny app one... will look into this
- for the lastest fontawesome version I'm not sure - I did think about that when I was pasting it in but forgot to follow it up
- Will change the shiny template author line
- Will also add a basic data table and plotly plot

**Comment by alan-y** [comment]
Thanks again @RosalynLP for all this work. We will need to make some changes to get this to work as the `inst` folder is only there for the package developer and not for the user when the phstemplates package gets installed. What happens is that when the package gets installed, folders called `images` and `text` will appear on the top level of the package and I think the user accesses these with e.g. `system.file(package = "phstemplates", "images", "phs-logo.png")` so the shiny template and functions will need to use this instead.

As we are including images and icons in the package, then you will need to remove from `.Rbuildignore`, `\.css$`, `\.png`, `\.ico` so that these get built with the package.

In `.gitignore` for this package, it might be easiest if you remove `*.[tT][xX][tT]` so that the text file templates get uploaded to Github for other package developers as they will need these. In general, ignoring data files is not completely necessary for package development (in contrast to projects/publications we work on) as it's unlikely the package will contain data that can't be public - in that case, we would use Gitea.

Last thing is to please add yourself as an author in `DESCRIPTION` as you're making a significant contribution here :smile:

I can install the package to test that all the `inst` stuff works when this is ready.

**Comment by RosalynLP** [comment]
> system.file(package = "phstemplates", "images", "phs-logo.png")

Thanks @alan-y  that's really useful insight, I was just trying to work out how to access things properly in inst!

**Comment by RosalynLP** [comment]
@alan-y that's those changes made now, I tested it out and it was working for me, and fixed the issue with the images not copying across! I'm just a bit bemused by the failing checks, are they the new checks added by @Moohan ?

I'm getting 
```
You are not currently on a branch.
Please specify which branch you want to merge with.
```
as the reason for those two failures, so wondering if it's something awry with the virtual environment the test is done in?

**Comment by alan-y** [comment]
That's great and very quick thanks! I think the tests are failing because they may only work on the main branch - I'm not 100% sure about this though. Don't worry about it for now as I can look into once merged (if they are still failing). I'll give the package a quick test and feedback soon.

**Comment by alan-y** [comment]
I've tested and all the files from `inst` are copying in except the `.gitignore` file - this is because you've got in `^\\.gitignore$` in  `.Rbuildignore` so this file doesn't get installed for the user. I'd probably just store the gitignore stuff in a file called `gitignore.txt` or something and then read that in.

The overwrite option needs added to `phsproject.dcf` - the overwrite option still doesn't work for me but I'm happy to add this in and merge and leave that for further investigation later as if it's working for you and Ruben, it's likely to be a specific issue on my side - maybe with the version of RStudio I'm using.

Capture
Capture2

**Comment by RosalynLP** [comment]
@alan-y have migrated .gitignore to gitignore.txt as you suggested, and also added overwrite to project dcf. Just loaded the package again and double checked that overwrite is working for me for both project and shiny app on server and desktop. Not sure why it's not working for you, did you also try on server?

**Comment by alan-y** [comment]
> Just loaded the package again and double checked that overwrite is working for me for both project and shiny app on server and desktop. Not sure why it's not working for you, did you also try on server?

Thanks, it's all looking great. I tested the overwrite option on RStudio Server which works for me and I also tested with a different version of RStudio desktop (v1.3) which also worked. But when I try with RStudio Desktop v2022.07.0, it comes up with the error message shown in the previous screenshot. So my guess is that the overwrite option will no longer work when we update to newer versions of RStudio unfortunately. But it's fine to leave it as is for now and revisit later when we've rolled those new versions out.

I think there is one typo on line 67 of `README.md`, there is a redundant `]`
Also please increment version to 1.1.0
Happy to merge into main :smile:

**Comment by RosalynLP** [comment]
@alan-y that's those changes made shall I merge or do you want to?

Thanks so much for your help with this :)

**Comment by alan-y** [comment]
I'll merge it now, thanks again for all your work on this - next job is to talk about it and get feedback!

**Pull request merged**
