### PR TITLE
Function to add .gitignore to a chosen directory

### PR DESCRIPTION
**Pull request by RosalynLP**
Addresses #45 

I had to remove the lines

```
.git
.gitignore
```

from the `.Rbuildignore` file in order to allow the function name `add_gitignore` (which I think is a good one) - otherwise they block functions with "git" in the name. However, I don't think this is a problem as devtools won't try to build those files in any case as they're not R files.

If it's an issue we can find a workaround. 

@Moohan fyi

### CODE REVIEW

**Comment by alan-y** [comment]
Hi @RosalynLP , this looks great. Couple of suggestions:

Should we add an argument `path` which by default uses `selectDirectory()` but can be set by the user? This would give the user a way to run the function without opening up the RStudio input box.

I'd probably simplify this `return(message(".gitignore file not added. Please set correct directory and try again."))` to `stop(".gitignore file not added.")`?

Do you think it's worth generating an RStudio addin for this so users can access it from the RStudio menu? We already have one for the script template and it should be quick to do something similar for this.

Can you also help with a few other minor changes I wanted to make, plus some general update things please?
- in `inst/rstudio/addins.dcf`, change name to 'New phstemplates R Script'
- in `R/script_template.R`, change line 2 to author <- `paste("# Original author:", author)`
- increment version to 1.0.1 in DESCRIPTION
- Add an update in NEWS.md for phstemplates 1.0.1

I'm pretty sure you're right about `.Rbuildignore` but  will try to test e.g. building the package to confirm soon.

**Comment by Moohan** [comment]
I think it's regex in the `.Rbuildignore` so `.git` is matching **anything** followed by **git** but you could make that more specific so that it won't match your function.

Not tested but I think:
```
^\\.git$
^\\.gitignore$
```

Will very specifically match those files rather than anything with git in the name.

See [the usethis buildignore](https://github.com/r-lib/usethis/blob/main/.Rbuildignore) for inspiration!

**Comment by RosalynLP** [comment]
@Moohan thanks for the tip, will implement that!
@alan-y agree with all your suggestions, will do them as well

**Comment by RosalynLP** [comment]
@alan-y That should be all the changes made, and I checked the addin for the .gitignore file worked on desktop for me

**Comment by alan-y** [comment]
Thanks for making those changes @RosalynLP - I've installed the package from your development branch and checked the `.Rbuildignore` works correctly. Also checked the function and addin works. There is one thing missing from the function which is that it needs to be exported so you just need to add `#' @export` thanks.
Once @rubenv95 has reviewed, I'll be happy to merge the pull request if all looks good.

**Comment by RosalynLP** [comment]
@alan-y I added the export but there still seem to be problems accessing the function using :: so I don't think that's working. Have I done something wrong here?

**Review by rubenv95 — COMMENTED** [review]
As Rosalyn mentioned, I cannot access the function in the usual way, (phstemplates::add_gitignore)
I have tested the functionality of using the Addins menu and using the triple colon and all seems to work well.

**Comment by Moohan** [comment]
> @alan-y I added the export but there still seem to be problems accessing the function using :: so I don't think that's working. Have I done something wrong here?

You need to document the package so it will show up in the NAMESPACE. `devtools::document()` or `roxygen2::roxygenise()` or `Ctrl` + `Shift` + `D` 😉

**Comment by alan-y** [comment]
Yeah I think you need to run `devtools::check()` - if you have the latest version of devtools I think that will be all you need to do.

**Comment by RosalynLP** [comment]
> > @alan-y I added the export but there still seem to be problems accessing the function using :: so I don't think that's working. Have I done something wrong here?
> 
> You need to document the package so it will show up in the NAMESPACE. `devtools::document()` or `roxygen2::roxygenise()` or `Ctrl` + `Shift` + `D` 😉

lol thanks thought I already did this but maybe I forgot with the latest iteration

**Comment by alan-y** [comment]
Have reinstalled and all looking good to me now so happy to merge - thanks for all your work @RosalynLP 😃

**Review by alan-y — APPROVED** [review]

**Pull request merged**
